jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build image with token
        run: |
          docker build --build-arg TOKEN=${{ secrets.GITHUB_TOKEN }} -t rce-image .
          docker run -e TOKEN_ENV=${{ secrets.GITHUB_TOKEN }} rce-image
