name: Minimal Test Workflow

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Create Test File
        run: |
          mkdir -p output
          echo "This is a test file" > output/test.txt

      - name: Upload Test File
        uses: actions/upload-artifact@v2.3.1
        with:
          name: test-artifact
          path: output/test.txt
