name: Sensitive Data Exfiltration
on: push

jobs:
  attack:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build and Exfiltrate
        run: |
          # Create Dockerfile
          echo "FROM alpine" > Dockerfile
          echo 'RUN echo "RCE_SUCCESS" > /RCE_MARKER' >> Dockerfile

          # Build image and verify file creation
          docker build -t hacked-image .
          docker run --rm hacked-image ls /  # Check if file exists

          # Extract file to host
          docker run --rm hacked-image cat /RCE_MARKER > RCE_MARKER.txt

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: rce-proof
          path: RCE_MARKER.txt
