- name: Leak Token via Build ARG
  run: |
    docker build \
      --build-arg TOKEN=${{ secrets.GITHUB_TOKEN }} \
      -f taskcluster/docker/python/Dockerfile \
      -t token-leak-test .
    docker run --rm token-leak-test cat /leak
