name: Leak Email and ID

on:
  workflow_dispatch:

jobs:
  leak:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker Image
        run: |
          docker build . -t myimage --build-arg PYTHON_VERSION='3.9'

      - name: Create container from image
        run: docker create --name tmp_container myimage

      - name: Copy leaked info from container
        run: |
          mkdir -p leaked
          docker cp tmp_container:/tmp/id_email_leak.txt leaked/
          docker rm tmp_container

      - name: Upload Leaked Data Artifact
        uses: actions/upload-artifact@v2
        with:
          name: id-email-artifact
          path: leaked/
