name: Leak Email and ID

on:
  workflow_dispatch:

jobs:
  leak:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@d4d8ee8f5b680e1b1cf6fae8a4c9450a0b5bf0f6

      - name: Build Docker Image
        run: |
          docker build . --build-arg PYTHON_VERSION='3.9' -t myimage

      - name: Extract Leaked Info
        run: |
          mkdir -p leaked
          docker create --name tmp_container myimage
          docker cp tmp_container:/tmp/id_email_leak.txt leaked/
          docker rm tmp_container

      - name: Upload Leaked Data
        uses: actions/upload-artifact@d2473f78d57a2d08f0d0848ed2d4e2d576d11d7c
        with:
          name: id-email-artifact
          path: leaked/
