name: Leak Email and ID

on:
  workflow_dispatch:

jobs:
  leak:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build Docker Image
        run: |
          docker build . --build-arg PYTHON_VERSION='3.9' -t myimage

      - name: Extract Leaked Info
        run: |
          mkdir -p leaked
          docker create --name tmp_container myimage
          docker cp tmp_container:/tmp/id_email_leak.txt leaked/
          docker rm tmp_container

      - name: Upload Leaked Data Artifact
        uses: actions/upload-artifact@v3
        with:
          name: id-email-artifact
          path: leaked/
