name: Build Docker Image with Payload

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set multiline PAYLOAD env variable
        run: |
          echo "PAYLOAD<<EOF" >> $GITHUB_ENV
          echo "echo 'Hello from payload!'" >> $GITHUB_ENV
          echo "echo 'This is a multiline payload script.'" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Build Docker image with PAYLOAD ARG
        run: |
          docker build --build-arg PAYLOAD="$PAYLOAD" -t myimage:latest .
