name: Exploit Build and Leak

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set PAYLOAD variable
      run: |
        echo "PAYLOAD=$(cat << 'EOF'
        # Your payload script or commands here, multiline if needed
        echo 'Hello from payload!'
        EOF
        )" >> $GITHUB_ENV

    - name: Build Docker image and run leak script
      run: |
        docker build --build-arg PAYLOAD="$PAYLOAD" -t exploit-image .
        docker run --rm exploit-image cat /leaks.txt
