name: Sensitive Data Exfiltration
on: push

jobs:
  attack:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build and Exfiltrate
        run: |
          # Build Docker image and create marker file
          docker build -t hacked-image .

          # Extract the file from the container to the GitHub runner
          docker run --rm hacked-image cat /RCE_MARKER > RCE_MARKER.txt

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: leaked-data
          path: RCE_MARKER.txt
