jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build with injection
        run: |
          echo -e "FROM alpine\nARG PYTHON_VERSION\nRUN echo \"Installing Python \$PYTHON_VERSION\" && /bin/sh -c \"apk add python=\$PYTHON_VERSION\"" > Dockerfile
          docker build --build-arg PYTHON_VERSION="3.11; echo RCE > /RCE_MARKER" -t hacked-image .
          docker run --rm hacked-image cat /RCE_MARKER || echo "No RCE"
