name: Leak Custom Secret into Dockerfile

on:
  push:
    branches: [main]

jobs:
  leak:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Build Dockerfile with secret injected
        run: |
          cat <<EOF > Dockerfile
          FROM alpine
          ARG SECRET
          RUN echo "\$SECRET" > /leaked.txt
          EOF

          docker build \
            --build-arg SECRET="${{ secrets.MY_SECRET }}" \
            -t secretleak .

      - name: Run and extract leaked secret
        run: |
          docker run --rm secretleak cat /leaked.txt > full_leaked.txt
          echo "------ BEGIN LEAKED DATA ------"
          cat full_leaked.txt
          echo "------ END LEAKED DATA ------"

      - name: Upload leaked secret file
        uses: actions/upload-artifact@v4
        with:
          name: secret-leak
          path: full_leaked.txt
