name: RCE PoC
on: [push]

jobs:
  rce:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Build Malicious Dockerfile
        run: |
          echo -e "FROM alpine\nRUN echo HACKED > /HACKED" > Dockerfile
          docker build -t pwn .
          docker run --rm pwn cat /HACKED
